OBJ += base/gdt.o base/gdt2.o # gdt
OBJ += base/idt.o base/idt2.o # idt
OBJ += base/logging.o
OBJ += base/libc.o
OBJ += base/acpi.o
OBJ += base/int32_2.o
OBJ += base/text_draw.o
OBJ += base/malloc.o
OBJ += base/bios32.o
OBJ += base/crash.o