OBJ += drivers/terminal.o drivers/flanterm/flanterm.o drivers/flanterm/fb.o
OBJ += drivers/timer.o drivers/timer2.o
OBJ += drivers/vmsvga.o drivers/graphics.o
OBJ += drivers/pci.o
OBJ += drivers/kbd.o drivers/mouse.o
OBJ += drivers/rtl8139.o
OBJ += drivers/libstdcxx.o
OBJ += drivers/ahci.o drivers/ata.o
OBJ += drivers/memdsk.o